var course =
    [
        {id: 4589, name: 'HTML complete course', price: 1500, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 3489, name: 'Pure Javascript complete course', price: 3000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 3796, name: 'Bootstrap complete course', price: 2000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7441, name: 'Angular JS complete course', price: 5000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4547, name: 'C++ complete course', price: 1000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 6541, name: 'Django complete course', price: 4500, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7596, name: 'Java complete course', price: 8000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4175, name: 'Mongo DB complete course', price: 5500, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4789, name: 'Mysql complete course', price: 6300, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 5974, name: 'Node JS complete course', price: 8500, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 5644, name: 'PHP complete course', price: 4700, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4125, name: 'Python complete course', price: 10000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4974, name: 'React JS complete course', price: 12200, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 6554, name: 'Vue JS complete course', price: 7900, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7854, name: 'CSS complete course', price: 7900, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 

    ];

export default course;