var fakeData =
    [
        {id: 4589, instructor: 'Sir, Jhankar', name: 'HTML complete course', price: 1500, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 3489, instructor: 'Sir, Jhankar', name: 'Pure Javascript complete course', price: 3000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 3796, instructor: 'Sir, Jhankar', name: 'Bootstrap complete course', price: 2000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7441, instructor: 'Sir, Jhankar', name: 'Angular JS complete course', price: 5000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4547, instructor: 'Sir, Jhankar', name: 'C++ complete course', price: 1000, img: 'https://bit.ly/2EAdVLo',  description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 6541, instructor: 'Sir, Jhankar', name: 'Django complete course', price: 4500, img: 'https://bit.ly/2EAdVLo',  description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7596, instructor: 'Sir, Jhankar', name: 'Java complete course', price: 8000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4175, instructor: 'Sir, Jhankar', name: 'Mongo DB complete course', price: 5500, img: 'https://bit.ly/2EAdVLo',  description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4789, instructor: 'Sir, Jhankar', name: 'Mysql complete course', price: 6300,img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 5974, instructor: 'Sir, Jhankar', name: 'Node JS complete course', price: 8500, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 5644, instructor: 'Sir, Jhankar', name: 'PHP complete course', price: 4700, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4125, instructor: 'Sir, Jhankar', name: 'Python complete course', price: 10000, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4974, instructor: 'Sir, Jhankar', name: 'React JS complete course', price: 12200, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 6554, instructor: 'Sir, Jhankar', name: 'Vue JS complete course', price: 7900, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7854, instructor: 'Sir, Jhankar', name: 'CSS complete course', price: 7900, img: 'https://bit.ly/2EAdVLo', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 

    ];

export default fakeData;